name: GPS-INS-master

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Updates
      run: sudo apt-get update
    - name: Install Build Tools
      run: sudo apt install build-essential libtool autoconf unzip wget
    - name: Install Eigen
      run: sudo apt install libeigen3-dev
    - name: Install CMake
      run: sudo apt-get install cmake
    - name: Setup SSH Keys
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "{{ secrets.SSH_PRIVATE_KEY }}"
    - name: Create Build Directory and Run CMake
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
    - name: Build Project
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: cmake --build build --target all --config Release -- -j4
    - name: List Files
      run: ls build/
    #- name: Run Unit Tests
    #  run: cd build && ./test_gps_ins
